language: shell
dist: trusty
sudo: required

services:
  - docker

before_script:
    - cd docker
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml build
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml up -d
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml logs -f oms-loginservice &
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml exec oms-loginservice ash /usr/src/scripts/wait.sh


script:
    - sudo docker-compose -f docker-compose-secrets.yml -f docker-compose.yml exec oms-loginservice mix coveralls
